# Generated by Django 6.0.5 on 2026-05-06 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memo",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memos",
                to="memos.category",
            ),
        ),
    ]
