# Generated by Django 6.0.5 on 2026-05-07 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memos", "0003_seed_uncategorized"),
    ]

    operations = [
        migrations.AddField(
            model_name="memo",
            name="deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="memo",
            name="repeat",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly"),
                ],
                default="none",
                max_length=10,
            ),
        ),
    ]
