# Generated by Django 6.0.5 on 2026-05-07 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memos", "0004_memo_deleted_at_memo_repeat"),
    ]

    operations = [
        migrations.AddField(
            model_name="memo",
            name="images",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
