# Generated by Django 6.0.5 on 2026-05-08 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memos", "0005_memo_images"),
    ]

    operations = [
        migrations.AddField(
            model_name="memo",
            name="schedule_date",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
