server {
    listen 80;
    server_name 54.116.131.130;

    client_max_body_size 10M;

    location /static/ {
        alias /home/ec2-user/github/memo-app/staticfiles/;
        access_log off;
        expires 7d;
    }

    location / {
        proxy_pass http://127.0.0.1:8001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
